/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config wrangler.mirror.jsonc --env-interface MirrorRetryEnv --include-runtime false worker-mirror-configuration.d.ts` (hash: e352f5569a6bee7253043efe5a13d198)
interface __BaseEnv_MirrorRetryEnv {
	DB: D1Database;
	MIRROR_TARGET_URL: "https://uta-nihongo-davetchiu.davechiu.chatgpt.site/api/internal/mirror";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/mirror-retry");
	}
	interface Env extends __BaseEnv_MirrorRetryEnv {}
}
interface MirrorRetryEnv extends __BaseEnv_MirrorRetryEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MIRROR_TARGET_URL">> {}
}
